
FROM node:20-alpine AS development

WORKDIR /app


COPY client/package.json client/package-lock.json* ./


RUN npm install


COPY client .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]


FROM development AS builder


RUN npm run build


FROM node:20-alpine AS runner

WORKDIR /app


RUN npm install -g serve


COPY --from=builder /app/dist ./dist

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]